src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\DateTime()
     */
    private $date_start;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\DateTime()
     */
    private $date_end;

    /**
     * @ORM\Column(type="boolean")
     */
    private $disabled;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="create")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="update")
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\SwapService", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $swapService;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings", cascade={"persist"} )
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\BookingState", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $bookingState;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\BookingType", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $bookingType;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\BookingComment", mappedBy="booking")
     */
    private $bookingComments;

    public function __construct()
    {
        $this->bookingComments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->date_start;
    }

    public function setDateStart(\DateTimeInterface $date_start): self
    {
        $this->date_start = $date_start;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->date_end;
    }

    public function setDateEnd(\DateTimeInterface $date_end): self
    {
        $this->date_end = $date_end;

        return $this;
    }

    public function getDisabled(): ?bool
    {
        return $this->disabled;
    }

    public function setDisabled(bool $disabled): self
    {
        $this->disabled = $disabled;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getSwapService(): ?SwapService
    {
        return $this->swapService;
    }

    public function setSwapService(?SwapService $swapService): self
    {
        $this->swapService = $swapService;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getBookingState(): ?BookingState
    {
        return $this->bookingState;
    }

    public function setBookingState(?BookingState $bookingState): self
    {
        $this->bookingState = $bookingState;

        return $this;
    }

    public function getBookingType(): ?BookingType
    {
        return $this->bookingType;
    }

    public function setBookingType(?BookingType $bookingType): self
    {
        $this->bookingType = $bookingType;

        return $this;
    }

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Transaction")
     * @ORM\JoinColumn(nullable=false)
     */
    private $transaction;

    /**
     * @return Collection|BookingComment[]
     */
    public function getBookingComments(): Collection
    {
        return $this->bookingComments;
    }

    public function addBookingComment(BookingComment $bookingComment): self
    {
        if (!$this->bookingComments->contains($bookingComment)) {
            $this->bookingComments[] = $bookingComment;
            $bookingComment->setBooking($this);
        }

        return $this;
    }

    public function removeBookingComment(BookingComment $bookingComment): self
    {
        if ($this->bookingComments->contains($bookingComment)) {
            $this->bookingComments->removeElement($bookingComment);
            // set the owning side to null (unless already changed)
            if ($bookingComment->getBooking() === $this) {
                $bookingComment->setBooking(null);
            }
        }

        return $this;
    }

    public function getTransaction(): ?Transaction
    {
        return $this->transaction;
    }

    public function setTransaction(Transaction $transaction): self
    {
        $this->transaction = $transaction;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Validator\ValidatorInterface;

/**
 * @ORM\Entity
 * @UniqueEntity("email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string")
     */
    private $phone;

    /**
     * @ORM\Column(type="integer")
     */
    private $account;

    /**
     * @ORM\Column(type="boolean")
     */
    private $disabled;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;
    
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\SwapService", mappedBy="user")
     */
    private $swapServices;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="user")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\BookingComment", mappedBy="userSender")
     */
    private $bookingComments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Message", mappedBy="userSender")
     */
    private $messages;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Transaction", mappedBy="userSender")
     */
    private $transactions;

    /**
     *
     * @ORM\OneToOne(targetEntity="App\Entity\Image", inversedBy="user", cascade={"persist"})
     * @Assert\Valid()
     * @ORM\JoinColumn(nullable=true)
     */
    private $image;

    public function __construct()
    {
        $this->swapServices = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->bookingComments = new ArrayCollection();
        $this->messages = new ArrayCollection();
        $this->transactions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName()
    {
        return $this->first_name;
    }

    public function setFirstName( $first_name)
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getAccount(): ?int
    {
        return $this->account;
    }

    public function setAccount(int $account): self
    {
        $this->account = $account;

        return $this;
    }

    public function getDisabled(): ?bool
    {
        return $this->disabled;
    }

    public function setDisabled(bool $disabled): self
    {
        $this->disabled = $disabled;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|SwapService[]
     */
    public function getSwapServices(): Collection
    {
        return $this->swapServices;
    }

    public function addSwapService(SwapService $swapService): self
    {
        if (!$this->swapServices->contains($swapService)) {
            $this->swapServices[] = $swapService;
            $swapService->setUser($this);
        }

        return $this;
    }

    public function removeSwapService(SwapService $swapService): self
    {
        if ($this->swapServices->contains($swapService)) {
            $this->swapServices->removeElement($swapService);
            // set the owning side to null (unless already changed)
            if ($swapService->getUser() === $this) {
                $swapService->setUser(null);
            }
        }

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setUser($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getUser() === $this) {
                $booking->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|BookingComment[]
     */
    public function getBookingComments(): Collection
    {
        return $this->bookingComments;
    }

    public function addBookingComment(BookingComment $bookingComment): self
    {
        if (!$this->bookingComments->contains($bookingComment)) {
            $this->bookingComments[] = $bookingComment;
            $bookingComment->setUserSender($this);
        }

        return $this;
    }

    public function removeBookingComment(BookingComment $bookingComment): self
    {
        if ($this->bookingComments->contains($bookingComment)) {
            $this->bookingComments->removeElement($bookingComment);
            // set the owning side to null (unless already changed)
            if ($bookingComment->getUserSender() === $this) {
                $bookingComment->setUserSender(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setUserSender($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->contains($message)) {
            $this->messages->removeElement($message);
            // set the owning side to null (unless already changed)
            if ($message->getUserSender() === $this) {
                $message->setUserSender(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Transaction[]
     */
    public function getTransactions(): Collection
    {
        return $this->transactions;
    }

    public function addTransaction(Transaction $transaction): self
    {
        if (!$this->transactions->contains($transaction)) {
            $this->transactions[] = $transaction;
            $transaction->setUserSender($this);
        }

        return $this;
    }

    public function removeTransaction(Transaction $transaction): self
    {
        if ($this->transactions->contains($transaction)) {
            $this->transactions->removeElement($transaction);
            // set the owning side to null (unless already changed)
            if ($transaction->getUserSender() === $this) {
                $transaction->setUserSender(null);
            }
        }

        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($file)
    {
        $this->image = $file;

        return $this;
    }
}

src/Controller/CoreController.php
<?php

declare(strict_types = 1);
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Translation\TranslatorInterface;

class CoreController extends AbstractController
{
    /**
     * @Route("/", name="core_home")
     */
    public function index(TranslatorInterface $translator)
    {
        return $this->render('core/index.html.twig', [
            'controller_name' => 'CoreController',
        ]);
    }
}

templates/core/dashboard/nextSwapReceived.html.twig
<div id="panelClickable" class="panel panel-info shadow account">
    <div class="panel-heading">
        <span class="titreCompte"><h3 class="panel-title">{{ 'core.dashboard.block_next_swap_toReceived.title'|trans }} <span class="badge"></span></h3><span>
        <span class="pull-right clickable"><i class="glyphicon glyphicon-chevron-down"></i></span>
    </div>
    <div id="panelClickableBody" class="panel-body">
        {% for bookingDone in bookingsDone %}
            {% if bookingDone.bookingState.label == 'Accepted' %}
                <table>
                    <thead>
                        <tr>
                            <td>Statut</td>
                            <td>Date/Service</td>
                            <td>Membre</td>
                            <td>Action</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ bookingDone.bookingState.label }}</td>
                            <td>
                                </br>
                                Du : {{ bookingDone.dateStart|date('d-m-Y') }}</br>
                                Au : {{ bookingDone.dateEnd|date('d-m-Y') }}
                            </td>
                            <td>
                                {{ bookingDone.swapService.user.lastName }} {{ bookingDone.swapService.user.lastName }}
                            </td>
                            <td>
                                <!-- Button trigger modal -->
                                <button class="btn btn-danger raleway400 text-center col-xs-94 col-xs-offset-1" data-toggle="modal" data-target="#modalRequestSent"><span class="glyphicon glyphicon-remove"></span></button>
                                </button>
                                <!-- Modal -->
                                <div class="modal fade" id="modalRequestSent" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                Etes-vous sûr de vouloir refuser ce service ?
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                <a href="{{ path('swap_booking_canceled', {'bookingId': bookingDone.id })}}">
                                                    <button class="btn btn-danger raleway400 text-center col-xs-94 col-xs-offset-1"><span class="glyphicon glyphicon-remove"></span></button>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            {% endif %}
        {% endfor %}
    </div>
</div>

templates/core/dashboard/nextSwapToRender.html.twig
<div id="panelClickable" class="panel panel-info shadow account">
    <div class="panel-heading">
        <span class="titreCompte"><h3 class="panel-title">{{ 'core.dashboard.block_next_swap_toGive.title'|trans }} <span class="badge"></span></h3><span>
        <span class="pull-right clickable"><i class="glyphicon glyphicon-chevron-down"></i></span>
    </div>
    <div id="panelClickableBody" class="panel-body">
        <table>
            <thead>
                <tr>
                    <td>Date/Service</td>
                    <td>Membre</td>
                    <td>Action</td>
                </tr>
            </thead>
            {% for swapService in swapServices %}
                {% for booking in swapService.bookings %}
                    {% if booking.bookingState.label == 'Accepted' %}
                        <tbody>
                            <tr>
                                <td>
                                    </br>
                                    Du : {{ booking.dateStart|date('d-m-Y') }} </br>
                                    Au : {{ booking.dateEnd|date('d-m-Y') }}
                                </td>
                                <td>
                                    {{ booking.user.firstName }} {{ booking.user.lastName }}
                                </td>
                                <td>
                                    <!-- Button trigger modal -->
                                    <button class="btn btn-danger raleway400 text-center col-xs-94 col-xs-offset-1" data-toggle="modal" data-target="#modalRequestSent"><span class="glyphicon glyphicon-remove"></span></button>
                                    </button>
                                    <!-- Modal -->
                                    <div class="modal fade" id="modalRequestSent" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    Etes-vous sûr de vouloir refuser ce service ?
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                    <a href="{{ path('swap_booking_canceled', {'bookingId': booking.id })}}">
                                                        <button class="btn btn-danger raleway400 text-center col-xs-94 col-xs-offset-1"><span class="glyphicon glyphicon-remove"></span></button>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    {% endif %}
                {% endfor %}
            {% endfor %}
        </table>
    </div>
</div>

templates/core/dashboard/requestReceived.html.twig
<div id="panelClickable" class="panel panel-info shadow account">
    <div class="panel-heading">
        <span class="titreCompte"><p>{{ 'core.dashboard.block_request_received.title'|trans }}</p><span>
        <span class="pull-right clickable"><i class="glyphicon glyphicon-chevron-down"></i></span>
    </div>
    <div id="panelClickableBody" class="panel-body">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <td>Statut</td>
                        <td>Date/Service</td>
                        <td>Membre</td>
                        <td>Total SwapPoints</td>
                        <td>Action</td>
                    </tr>
                </thead>
                {% for swapService in swapServices %}
                    {% for booking in swapService.bookings %}
                        {% if booking.bookingState.label == 'Waiting' %}
                        <tbody>
                            <tr>
                                <td> En Attente</td>
                                <td id="table">
                                    Du : {{ booking.dateStart|date('d-m-Y') }} </br>
                                    Au : {{ booking.dateEnd|date('d-m-Y') }}
                                </td>
                                <td>
                                    {{ booking.user.firstName }} {{ booking.user.lastName }}
                                </td>
                                <td>{{ booking.transaction.amount }}</td>
                                <td id="actionBtn">
                                    <div>
                                        <a href="{{ path('swap_booking_accepted', {'bookingId': booking.id })}}">
                                        <button class="btn btn-primary raleway400 text-center col-xs-94 col-xs-offset-1"><span class="glyphicon glyphicon-ok"></button>
                                    </div>
                                    </a>
                                    </div>
                                    <!-- Button trigger modal -->
                                    <button class="btn btn-danger raleway400 text-center col-xs-94 col-xs-offset-1" data-toggle="modal" data-target="#exampleModal"><span class="glyphicon glyphicon-remove"></span></button>
                                    </button>
                                    <!-- Modal -->
                                    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    Etes-vous sûr de vouloir refuser ce service ?
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                    <a href="{{ path('swap_booking_canceled', {'bookingId': booking.id })}}">
                                                        <button class="btn btn-danger raleway400 text-center col-xs-94 col-xs-offset-1"><span class="glyphicon glyphicon-remove"></span></button>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            </table>
        </div>
    </div>
</div>

templates/core/dashboard/requestSent.html.twig
<div id="panelClickable" class="panel panel-info shadow account">
    <div class="panel-heading">
        <span class="titreCompte"><p>{{ 'core.dashboard.block_request_sent.title'|trans }} <span class="badge"></span></p><span>
        <span class="pull-right clickable"><i class="glyphicon glyphicon-chevron-down"></i></span>
    </div>
    <div id="panelClickableBody" class="panel-body">
        <table>
            <thead>
                <tr>
                    <td>Statut</td>
                    <td>Date/Service</td>
                    <td>Membre</td>
                    <td>Total SwapPoints</td>
                    <td>Action</td>
                </tr>
            </thead>
            {% for bookingDone in bookingsDone %}
                {% if bookingDone.bookingState.label == 'Waiting' %}
                    <tbody>
                        <tr>
                            <td> {{ bookingDone.bookingState.label }} </td>
                            <td>
                                </br>
                                Du : {{ bookingDone.dateStart|date('d-m-Y') }} </br>
                                Au : {{ bookingDone.dateStart|date('d-m-Y') }}
                            </td>
                            <td>
                                {{ bookingDone.swapService.user.lastName }} {{ bookingDone.swapService.user.lastName }}
                            </td>
                            <td>{{ bookingDone.transaction.amount }}</td>
                            <td>
                                <!-- Button trigger modal -->
                                <button class="btn btn-danger raleway400 text-center col-xs-94 col-xs-offset-1" data-toggle="modal" data-target="#modalRequestSent"><span class="glyphicon glyphicon-remove"></span></button>
                                </button>
                                <!-- Modal -->
                                <div class="modal fade" id="modalRequestSent" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                Etes-vous sûr de vouloir refuser ce service ?
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                <a href="{{ path('swap_booking_canceled', {'bookingId': bookingDone.id })}}">
                                                    <button class="btn btn-danger raleway400 text-center col-xs-94 col-xs-offset-1"><span class="glyphicon glyphicon-remove"></span></button>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                {% endif %}
            {% endfor %}
        </table>
    </div>
</div>