src/Entity/SwapService.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Serializer\Serializer as Serializer;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SwapServiceRepository")
 */
class SwapService
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $quantity;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    private $people_quantity;

    /**
     * @ORM\Column(type="integer")
     */
    private $latitude;

    /**
     * @ORM\Column(type="integer")
     */
    private $longitude;

    /**
     * @ORM\Column(type="string", length=250)
     */
    private $adress_1;

    /**
     * @ORM\Column(type="string", length=250, nullable=true)
     */
    private $adress_2;

    /**
     * @ORM\Column(type="string", length=250, nullable=true))
     */
    private $adress_3;

    /**
     * @ORM\Column(type="string", length=45)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=45)
     */
    private $region;

    /**
     * @ORM\Column(type="string", length=45)
     */
    private $country;

    /**
     * @ORM\Column(type="boolean")
     */
    private $disabled;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="swapServices", cascade={"persist"} )
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\SwapServiceType", inversedBy="swapServices",  cascade={"persist"} ))
     * @ORM\JoinColumn(nullable=true)
     */
    private $swapServiceType;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="swapService")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Transaction", mappedBy="swapService")
     */
    private $transactions;

    public function __construct()
    {
        $this->bookings = new ArrayCollection();
        $this->transactions = new ArrayCollection();
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(?int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getPeopleQuantity(): ?string
    {
        return $this->people_quantity;
    }

    public function setPeopleQuantity(?string $people_quantity): self
    {
        $this->people_quantity = $people_quantity;

        return $this;
    }

    public function getLatitude(): ?int
    {
        return $this->latitude;
    }

    public function setLatitude(int $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?int
    {
        return $this->longitude;
    }

    public function setLongitude(int $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getAdress1(): ?string
    {
        return $this->adress_1;
    }

    public function setAdress1(string $adress_1): self
    {
        $this->adress_1 = $adress_1;

        return $this;
    }

    public function getAdress2(): ?string
    {
        return $this->adress_2;
    }

    public function setAdress2(string $adress_2): self
    {
        $this->adress_2 = $adress_2;

        return $this;
    }

    public function getAdress3(): ?string
    {
        return $this->adress_3;
    }

    public function setAdress3(string $adress_3): self
    {
        $this->adress_3 = $adress_3;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getRegion(): ?string
    {
        return $this->region;
    }

    public function setRegion(string $region): self
    {
        $this->region = $region;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getDisabled(): ?bool
    {
        return $this->disabled;
    }

    public function setDisabled(bool $disabled): self
    {
        $this->disabled = $disabled;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getSwapServiceType(): ?SwapServiceType
    {
        return $this->swapServiceType;
    }

    public function setSwapServiceType(?SwapServiceType $swapServiceType): self
    {
        $this->swapServiceType = $swapServiceType;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setSwapService($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getSwapService() === $this) {
                $booking->setSwapService(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Transaction[]
     */
    public function getTransactions(): Collection
    {
        return $this->transactions;
    }

    public function addTransaction(Transaction $transaction): self
    {
        if (!$this->transactions->contains($transaction)) {
            $this->transactions[] = $transaction;
            $transaction->setSwapService($this);
        }

        return $this;
    }

    public function removeTransaction(Transaction $transaction): self
    {
        if ($this->transactions->contains($transaction)) {
            $this->transactions->removeElement($transaction);
            // set the owning side to null (unless already changed)
            if ($transaction->getSwapService() === $this) {
                $transaction->setSwapService(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Validator\ValidatorInterface;

/**
 * @ORM\Entity
 * @UniqueEntity("email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string")
     */
    private $phone;

    /**
     * @ORM\Column(type="integer")
     */
    private $account;

    /**
     * @ORM\Column(type="boolean")
     */
    private $disabled;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;
    
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\SwapService", mappedBy="user")
     */
    private $swapServices;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="user")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\BookingComment", mappedBy="userSender")
     */
    private $bookingComments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Message", mappedBy="userSender")
     */
    private $messages;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Transaction", mappedBy="userSender")
     */
    private $transactions;

    /**
     *
     * @ORM\OneToOne(targetEntity="App\Entity\Image", inversedBy="user", cascade={"persist"})
     * @Assert\Valid()
     * @ORM\JoinColumn(nullable=true)
     */
    private $image;

    public function __construct()
    {
        $this->swapServices = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->bookingComments = new ArrayCollection();
        $this->messages = new ArrayCollection();
        $this->transactions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName()
    {
        return $this->first_name;
    }

    public function setFirstName( $first_name)
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getAccount(): ?int
    {
        return $this->account;
    }

    public function setAccount(int $account): self
    {
        $this->account = $account;

        return $this;
    }

    public function getDisabled(): ?bool
    {
        return $this->disabled;
    }

    public function setDisabled(bool $disabled): self
    {
        $this->disabled = $disabled;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|SwapService[]
     */
    public function getSwapServices(): Collection
    {
        return $this->swapServices;
    }

    public function addSwapService(SwapService $swapService): self
    {
        if (!$this->swapServices->contains($swapService)) {
            $this->swapServices[] = $swapService;
            $swapService->setUser($this);
        }

        return $this;
    }

    public function removeSwapService(SwapService $swapService): self
    {
        if ($this->swapServices->contains($swapService)) {
            $this->swapServices->removeElement($swapService);
            // set the owning side to null (unless already changed)
            if ($swapService->getUser() === $this) {
                $swapService->setUser(null);
            }
        }

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setUser($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getUser() === $this) {
                $booking->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|BookingComment[]
     */
    public function getBookingComments(): Collection
    {
        return $this->bookingComments;
    }

    public function addBookingComment(BookingComment $bookingComment): self
    {
        if (!$this->bookingComments->contains($bookingComment)) {
            $this->bookingComments[] = $bookingComment;
            $bookingComment->setUserSender($this);
        }

        return $this;
    }

    public function removeBookingComment(BookingComment $bookingComment): self
    {
        if ($this->bookingComments->contains($bookingComment)) {
            $this->bookingComments->removeElement($bookingComment);
            // set the owning side to null (unless already changed)
            if ($bookingComment->getUserSender() === $this) {
                $bookingComment->setUserSender(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setUserSender($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->contains($message)) {
            $this->messages->removeElement($message);
            // set the owning side to null (unless already changed)
            if ($message->getUserSender() === $this) {
                $message->setUserSender(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Transaction[]
     */
    public function getTransactions(): Collection
    {
        return $this->transactions;
    }

    public function addTransaction(Transaction $transaction): self
    {
        if (!$this->transactions->contains($transaction)) {
            $this->transactions[] = $transaction;
            $transaction->setUserSender($this);
        }

        return $this;
    }

    public function removeTransaction(Transaction $transaction): self
    {
        if ($this->transactions->contains($transaction)) {
            $this->transactions->removeElement($transaction);
            // set the owning side to null (unless already changed)
            if ($transaction->getUserSender() === $this) {
                $transaction->setUserSender(null);
            }
        }

        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($file)
    {
        $this->image = $file;

        return $this;
    }
}

templates/core/swapService/booking.html.twig
{% extends 'base.html.twig' %}

{% block title %}Search{% endblock %}
{% block stylesheets %}
    <link href="{{ asset('build/booking.css') }}" rel="stylesheet" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
{% endblock %}
{% block body %}
    <div class="containerBooking">
        <div class="row">
            <div class="col-md-3 col-md-offset-1">
                <div class="panel-body shadow Compte">
                    {% if swap.user.image == null %}
                        <img class="img-responsive" src="{{asset('build/static/silhouette.png') }}">
                    {% else %}
                        <img class="img-responsive" src="{{asset('build/uploads/pictures/optimized/' ~ swap.user.image.image) }}">
                    {% endif %}
                    <p>{{ swap.user.firstName }} {{ swap.user.lastName }}</p>
                    <a href="asset('build/static/silhouette.png')">
                        <a id="btnSendMessage" href="{{ path('app_message_send', {'serviceId': swapId, 'receiverId': swap.user.id })}}" type="button" class="btn btn-primary text-center col-md-12">Envoyer un message</a>
                    </a>
                </div>
            </div>
            <div class="col-md-7">
                <div class="panel-body shadow Compte">
                    <h3>Reservation</h3>
                    <span class="sousTitre"><p>Effectuer une réservation</p><span>
                    {{ form_start(form) }}
                    {# Les erreurs générales du formulaire. #}
                    <label>Choisissez vos dates : </label>
                    <input type="text" name="daterange"  class="form-control form-control" required="required" />
                    {{ form_row(form.date_start, { 'attr': { 'class' : 'form-control' }} ) }}
                    {{ form_row(form.date_end, { 'attr': { 'class' : 'form-control' }} ) }}
                    <div id="total">Nombre de SwapPoints:&nbsp; <div id="nbrSwaps">0</div></div>
                    {{ form_row(form.save, { 'label': 'Demande de réservation', 'attr': { 'class' : 'col-sm-offset-18 btn btn-primary ' }} ) }}
                    {{ form_rest(form, { 'attr': { 'class' : 'form-control' }} ) }}
                    {{ form_end(form, { 'attr': { 'class' : 'form-control' }} ) }}
                </div>
            </div>
        </div>
    </div>
    </div>
    <div class="js-user-rating" data-is-authenticated="{{ dateBooked }}"></div>
    <div class="amount" data-is-authenticated="{{ amount }}"></div>
{% endblock %}
{% block javascripts %}
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <script type="text/javascript">
        var dateBooked = document.querySelector('.js-user-rating');
        var dateBooked = dateBooked.dataset.isAuthenticated;
        var jsonDecodeArray = JSON.parse(dateBooked);

        var amount = document.querySelector('.amount');
        var amount = amount.dataset.isAuthenticated;
        var jsonDecodeAmount = JSON.parse(amount);

        $('input[name="daterange"]').daterangepicker({
            "locale": {
                "format": "DD/MM/YYYY",
                "separator": " - ",
                "applyLabel": "Valider",
                "cancelLabel": "Annuler",
                "fromLabel": "De",
                "toLabel": "à",
                "customRangeLabel": "Custom",
                "daysOfWeek": [
                    "Dim",
                    "Lun",
                    "Mar",
                    "Mer",
                    "Jeu",
                    "Ven",
                    "Sam"
                ],
                "monthNames": [
                    "Janvier",
                    "Février",
                    "Mars",
                    "Avril",
                    "Mai",
                    "Juin",
                    "Juillet",
                    "Août",
                    "Septembre",
                    "Octobre",
                    "Novembre",
                    "Décembre"
                ],
                "firstDay": 1
            },
            'isInvalidDate': function (date) {
                if (moment(date).isBefore(moment().format('YYYY-MM-DD'))) {
                    return true;
                }
                for (var i = 0; i < jsonDecodeArray.length; i++) {
                    var dateStart = '20' + jsonDecodeArray[i].dateStart.year + '-' + jsonDecodeArray[i].dateStart.month + '-' + jsonDecodeArray[i].dateStart.day;
                    var dateEnd = '20' + jsonDecodeArray[i].dateEnd.year + '-' + jsonDecodeArray[i].dateEnd.month + '-' + jsonDecodeArray[i].dateEnd.day;
                    if (date.format('YYYY-MM-DD') == dateStart) {
                        return true;
                    }
                    if (date.format('YYYY-MM-DD') == dateEnd) {
                        return true;
                    }
                    if (moment(date).isAfter(dateStart) == true && moment(date).isBefore(dateEnd) == true) {
                        return true;
                    }
                }
            },
        });
        $('input[name="daterange"]').change(function(){
            var startDate = $('input[name="daterange"]').data('daterangepicker').startDate._d;
            var endDate = $('input[name="daterange"]').data('daterangepicker').endDate._d;

            document.getElementById("booking_form_date_start").value = moment(startDate).format('YYYY-MM-DD');
            document.getElementById("booking_form_date_end").value = moment(endDate).format('YYYY-MM-DD');;
            var tmp = endDate - startDate;
            var diff = {};
            tmp = Math.floor(tmp/1000);             // Nombre de secondes entre les 2 dates
            diff.sec = tmp % 60;                    // Extraction du nombre de secondes

            tmp = Math.floor((tmp-diff.sec)/60);    // Nombre de minutes (partie entière)
            diff.min = tmp % 60;                    // Extraction du nombre de minutes

            tmp = Math.floor((tmp-diff.min)/60);    // Nombre d'heures (entières)
            diff.hour = tmp % 24;                   // Extraction du nombre d'heures

            tmp = Math.floor((tmp-diff.hour)/24);   // Nombre de jours restants
            diff.day = tmp;

            var totalAmount = diff.day * jsonDecodeAmount;
            $('#nbrSwaps').text('       ' +  totalAmount);
        });
    </script>
{% endblock %}

templates/core/swapService/formDetailsSwapService.html.twig
{% extends 'base.html.twig' %}

{% block title %}Search{% endblock %}
{% block stylesheets %}
    <link href="{{ asset('build/formSwapService.css') }}" rel="stylesheet" />
{% endblock %}
{% block body %}
    <div class="formSwapServiceContainer">
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <div class="panel-body shadow FormulaireDetailsSwap">
                <h3>Ajouter un Swap</h3>
                <span class="sousTitre"><p>2. Decrire le Swap</p><span>
				{{ form_start(form) }}
                {# Les erreurs générales du formulaire. #}
                {{ form_errors(form, { 'attr': { 'class' : 'form-control' }} ) }}
                {{ form_row(form.people_quantity, { 'attr': { 'class' : 'form-control' }} ) }}
                {{ form_row(form.adress_1, { 'attr': { 'class' : 'form-control' }} ) }}
                {{ form_row(form.save, { 'attr': { 'class' : 'col-sm-offset-18 btn btn-primary ' }} ) }}
                {{ form_rest(form, { 'attr': { 'class' : 'form-control' }} ) }}
                {{ form_end(form, { 'attr': { 'class' : 'form-control' }} ) }}
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block javascripts %}
    <script src="{{ asset('build/formSwapService.js') }}"></script>
{% endblock %}

templates/core/swapService/formSwapService.html.twig
{% extends 'base.html.twig' %}
{% block title %}Search{% endblock %}
{% block stylesheets %}
    <link href="{{ asset('build/formSwapService.css') }}" rel="stylesheet" />
{% endblock %}
{% block body %}
    <div class="formSwapServiceContainer">
        <div class="row">
            <div class="col-md-offset-2 col-md-8">
                <div class="panel-body shadow FormulaireAjouterSwap">
                    <h3>Ajouter un Swap</h3>
                    <span class="sousTitre"><p>1. Choisir une catégorie de Swap</p><span>
                    {{ form_start(form) }}
                    {# Les erreurs générales du formulaire. #}
                    {{ form_errors(form, { 'attr': { 'class' : 'form-control' }} ) }}
                    {{ form_row(form.label, { 'attr': { 'class' : 'form-control' }} ) }}
                    {{ form_row(form.save, { 'attr': { 'class' : 'col-sm-offset-18 btn btn-primary ' }} ) }}
                    {{ form_rest(form, { 'attr': { 'class' : 'form-control' }} ) }}
                    {{ form_end(form, { 'attr': { 'class' : 'form-control' }} ) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script src="{{ asset('build/formSwapService.js') }}"></script>
{% endblock %}

templates/core/swapService/mySwapsServices.html.twig
{% extends 'base.html.twig' %}

{% block title %}My Swaps{% endblock %}
{% block stylesheets %}
    <link href="{{ asset('build/mySwapsServices.css') }}" rel="stylesheet" />
{% endblock %}
{% block body %}
<div class="mySwapsContainer">
    <div class="row">
        <div class="col-md-offset-1 col-md-10">
            <div class="panel panel-default shadow">
                <h1>Mes Swaps</h1>
                {% for service in services %}
                    {% if service.disabled != 0 %}
                    <div  id="rowMySwaps" class="row">
                        <div class="col-xs-offset-1 col-xs-10">
                            <a href="">
                                <div id="mySwap" class="panel panel-default">
                                    <div class="row">
                                        <div class="col-xs-offset-1  col-xs-8 mySwaps">
                                            <p> {{ service.adress1 }} </p>
                                            <p> {{ service.swapServiceType.label }} </p>
                                        </div>
                                        <a href="{{ path('swap_delete', {'serviceId': service.id })}}">
                                            <div class="col-md-2  deletedSwap ">
                                                <span class="glyphicon glyphicon-remove fontbig hidden-xs"></span>
                                                <br>
                                                <p>Supprimer</p>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block javascripts %}
    <script src="{{ asset('build/mySwapsServices.js') }}"></script>
{% endblock %}

templates/core/swapService/search.html.twig
{% extends 'base.html.twig' %}

{% block title %}Search{% endblock %}
{% block stylesheets %}
    <link href="{{ asset('build/searchSwapService.css') }}" rel="stylesheet" />
{% endblock %}
{% block body %}
    <div id="mapContainer">
        <div id="map"></div>
    </div>
    <div class="row">
        <div id="containerResults">
            <div id="resultSearch">

            </div>
        </div>
    </div>
    <footer class="page-footer font-small blue pt-4">

        <div class="footer-copyright text-center py-3">© 2018 Copyright:
            <a href="https://mdbootstrap.com/education/bootstrap/"> MDBootstrap.com</a>
        </div>
    </footer>
{% endblock %}
{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/gasparesganga-jquery-loading-overlay@2.1.6/dist/loadingoverlay.min.js"></script>
    <script src="{{ asset('build/searchSwapService.js') }}"></script>
{% endblock %}