src/Entity/Message.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MessageRepository")
 */
class Message
{
    public function __construct() {
        $this->SetDisabled(0);
    }

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var int
     *
     * @ORM\Column(name="serviceId", type="integer", nullable=true)
     */
    private $serviceId;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="create")
     */
    private $date_send;

    /**
     *
     * @Assert\Length(
     *      min = 2,
     *      minMessage = "Votre message doit faire au moins {{ limit }} characters"
     * )
     * @ORM\Column(type="string", length=500)
     */
    private $content;

    /**
     * @ORM\Column(type="boolean")
     */
    private $disabled;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="create")
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="messages")
     * @ORM\JoinColumn(nullable=false)
     */
    private $userSender;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="messages")
     * @ORM\JoinColumn(nullable=false)
     */
    private $userReceiver;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateSend(): ?\DateTimeInterface
    {
        return $this->date_send;
    }

    public function setDateSend(\DateTimeInterface $date_send): self
    {
        $this->date_send = $date_send;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function getServiceId(): ?string
    {
        return $this->serviceId;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function setServiceId(string $serviceId): self
    {
        $this->serviceId = $serviceId;

        return $this;
    }

    public function getDisabled(): ?bool
    {
        return $this->disabled;
    }

    public function getParentId(): ?int
    {
        return $this->parentId;
    }

    public function setDisabled(bool $disabled): self
    {
        $this->disabled = $disabled;

        return $this;
    }

    public function setParentId(int $parentId): self
    {
        $this->parentId = $parentId;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUserSender(): ?User
    {
        return $this->userSender;
    }

    public function setUserSender(?User $userSender): self
    {
        $this->userSender = $userSender;

        return $this;
    }

    public function getUserReceiver(): ?User
    {
        return $this->userReceiver;
    }

    public function setUserReceiver(?User $userReceiver): self
    {
        $this->userReceiver = $userReceiver;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Validator\ValidatorInterface;

/**
 * @ORM\Entity
 * @UniqueEntity("email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string")
     */
    private $phone;

    /**
     * @ORM\Column(type="integer")
     */
    private $account;

    /**
     * @ORM\Column(type="boolean")
     */
    private $disabled;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;
    
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\SwapService", mappedBy="user")
     */
    private $swapServices;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="user")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\BookingComment", mappedBy="userSender")
     */
    private $bookingComments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Message", mappedBy="userSender")
     */
    private $messages;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Transaction", mappedBy="userSender")
     */
    private $transactions;

    /**
     *
     * @ORM\OneToOne(targetEntity="App\Entity\Image", inversedBy="user", cascade={"persist"})
     * @Assert\Valid()
     * @ORM\JoinColumn(nullable=true)
     */
    private $image;

    public function __construct()
    {
        $this->swapServices = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->bookingComments = new ArrayCollection();
        $this->messages = new ArrayCollection();
        $this->transactions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName()
    {
        return $this->first_name;
    }

    public function setFirstName( $first_name)
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getAccount(): ?int
    {
        return $this->account;
    }

    public function setAccount(int $account): self
    {
        $this->account = $account;

        return $this;
    }

    public function getDisabled(): ?bool
    {
        return $this->disabled;
    }

    public function setDisabled(bool $disabled): self
    {
        $this->disabled = $disabled;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|SwapService[]
     */
    public function getSwapServices(): Collection
    {
        return $this->swapServices;
    }

    public function addSwapService(SwapService $swapService): self
    {
        if (!$this->swapServices->contains($swapService)) {
            $this->swapServices[] = $swapService;
            $swapService->setUser($this);
        }

        return $this;
    }

    public function removeSwapService(SwapService $swapService): self
    {
        if ($this->swapServices->contains($swapService)) {
            $this->swapServices->removeElement($swapService);
            // set the owning side to null (unless already changed)
            if ($swapService->getUser() === $this) {
                $swapService->setUser(null);
            }
        }

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setUser($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getUser() === $this) {
                $booking->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|BookingComment[]
     */
    public function getBookingComments(): Collection
    {
        return $this->bookingComments;
    }

    public function addBookingComment(BookingComment $bookingComment): self
    {
        if (!$this->bookingComments->contains($bookingComment)) {
            $this->bookingComments[] = $bookingComment;
            $bookingComment->setUserSender($this);
        }

        return $this;
    }

    public function removeBookingComment(BookingComment $bookingComment): self
    {
        if ($this->bookingComments->contains($bookingComment)) {
            $this->bookingComments->removeElement($bookingComment);
            // set the owning side to null (unless already changed)
            if ($bookingComment->getUserSender() === $this) {
                $bookingComment->setUserSender(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setUserSender($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->contains($message)) {
            $this->messages->removeElement($message);
            // set the owning side to null (unless already changed)
            if ($message->getUserSender() === $this) {
                $message->setUserSender(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Transaction[]
     */
    public function getTransactions(): Collection
    {
        return $this->transactions;
    }

    public function addTransaction(Transaction $transaction): self
    {
        if (!$this->transactions->contains($transaction)) {
            $this->transactions[] = $transaction;
            $transaction->setUserSender($this);
        }

        return $this;
    }

    public function removeTransaction(Transaction $transaction): self
    {
        if ($this->transactions->contains($transaction)) {
            $this->transactions->removeElement($transaction);
            // set the owning side to null (unless already changed)
            if ($transaction->getUserSender() === $this) {
                $transaction->setUserSender(null);
            }
        }

        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($file)
    {
        $this->image = $file;

        return $this;
    }
}

src/Controller/CoreController.php
<?php

declare(strict_types = 1);
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Translation\TranslatorInterface;

class CoreController extends AbstractController
{
    /**
     * @Route("/", name="core_home")
     */
    public function index(TranslatorInterface $translator)
    {
        return $this->render('core/index.html.twig', [
            'controller_name' => 'CoreController',
        ]);
    }
}

src/Controller/MessageController.php
<?php
/**
 * Created by PhpStorm.
 * User: annes
 * Date: 08/01/2019
 * Time: 13:53
 */

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Form\MessageFormType;
use App\Entity\Message;
use App\Entity\SwapService;
use App\Entity\User;
use App\Service\MessageManager;

/**
 * @IsGranted("ROLE_USER")
 */
class MessageController extends AbstractController
{
    /**
     * @Route("/mailbox", name="app_message_mailBox")
     */
    public function mailBox()
    {
        $userId = $this->getUser()->getId();

        $repository = $this->getDoctrine()->getRepository(Message::class);
        $messages = $repository->getMessagesByUser($userId);

        return $this->render('core/message/mailBox.html.twig', [
            'messages' => $messages,
            'idUser' => $userId,
        ]);
    }

    /**
     * @Route("/message/{serviceId}/{receiverId}", name="app_message_send")
     */
    public function send(Request $request, $serviceId, $receiverId, MessageManager $messageManager)
    {
        $form = $this->createForm(MessageFormType::class);
        $form->handleRequest($request);

        $user = $this->getUser();
        $repository = $this->getDoctrine()->getRepository(SwapService::class);
        $service = $repository->findOneBy(array('id' => $serviceId));
        $repository = $this->getDoctrine()->getRepository(User::class);
        $userReceiver = $repository->findOneBy(array('id' => $receiverId));

        if ($form->isSubmitted() && $form->isValid()) {
            $message  = $form->getData();
            $message->setUserSender($user);
            $message->setServiceId($serviceId);
            $message->setUserReceiver($userReceiver);
            $em = $this->getDoctrine()->getManager();
            $em->persist($message);
            $em->flush();
        }

        $messages = $this->getDoctrine()
            ->getRepository(Message::class)
            ->conversationRecovery($serviceId, $user->getId(), $receiverId);

        return $this->render('core/message/conversation.html.twig', array(
            'listMessage' => $messages,
            'service' => $service,
            'userId' => $user->getId(),
            'user' => $user,
            'form' => $form->createView(),
        ));
    }

    /**
     * @Route("/message/{id}", name="app_message_read")
     */
    public function read($id)
    {
        return $this->render('core/message/message.html.twig');
    }
}

templates/core/message/conversation.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - Index{% endblock %}

{% block stylesheets %}
    <link href="{{ asset('build/profile.css') }}" rel="stylesheet" />
    <link href="{{ asset('build/message.css') }}" rel="stylesheet" />
{% endblock %}
{% block body %}
    <div class="containerMessage">
    <div class="row">
    <!--    <div class="col-md-3 col-md-offset-1">
           <div class="panel-body shadow Compte">
                {% if service.user.id == userId %}
                    <div class="namePorfilConversation">{{ service.user.firstName }} {{ service.user.lastName }}</div>
                {% else %}
                    <div class="namePorfilConversation">{{ user.firstName }} {{ user.lastName }}</div>
                {% endif %}
            </div>
        </div> -->
        <div id="conversation-message" class="col-md-offset-2 col-md-8">
            <div id="bloc-message-conversation" class="panel-body shadow Compte">
                {{ form_start(form) }}
                {{ form_errors(form, { 'attr': { 'class' : 'form-control' }} ) }}
                {{ form_row(form.content, { 'attr': { 'class' : 'form-control' }} ) }}
                {{ form_row(form.save, { 'attr': { 'class' : 'btn btn-group pull-right' }} ) }}
                {{ form_rest(form, { 'attr': { 'class' : 'form-control' }} ) }}
                {{ form_end(form, { 'attr': { 'class' : 'form-control' }} ) }}
            </div>
            {% for message in listMessage %}
                {% if message.userSender.id == userId %}
                    <div class="row">
                        <div id="conversation-answer" class="col-xs-10">
                            <div id="bloc-author-conversation" class="panel-body shadow Compte">
                                <p>Le : {{ message.dateSend | date('d-m-Y H:i:s') }}</p>
                                {{ message.content }}
                            </div>
                        </div>
                        <div id="polygon" class="col-xs-1">
                            <svg width="100%" height="30" viewBox="0 0 100 100" preserveAspectRatio="none">
                                <polygon points="0,0 100,0 0,100" style="fill:rgba(163,210,240,1)" />
                            </svg>
                        </div>
                        <div id="silhouette" class="col-xs-1">
                            {% if message.userSender.image.image == null %}
                                <img class="img-responsive img-circle img-responsive" src="{{ asset('build/static/silhouette.png') }}">
                            {% else %}
                                <img class="img-responsive img-circle img-responsive"  src="{{asset('build/uploads/pictures/optimized/' ~ message.userSender.image.image) }}">
                            {% endif %}
                        </div>
                    </div>
                {% else %}
                    <div class="row">
                        <div id="silhouette" class="col-xs-1">
                            {% if message.userSender.image.image == null %}
                                <img class="img-responsive img-circle img-responsive" src="{{ asset('build/static/silhouette.png') }}">
                            {% else %}
                                <img class="img-responsive img-circle img-responsive"  src="{{asset('build/uploads/pictures/optimized/' ~ message.userSender.image.image) }}">
                            {% endif %}
                        </div>
                        <div id="polygon" class="col-xs-1">
                            <svg width="100%" height="30" viewBox="0 0 100 100" preserveAspectRatio="none">
                                <polygon points="0,0 100,0 100,100" style="fill:#fff" />
                            </svg>
                        </div>
                        <div id="conversation-answer" class="col-xs-10">
                            <div id="bloc-recipient-conversation" class="panel-body shadow Compte">
                                <p>Le : {{ message.dateSend | date('d-m-Y H:i:s')}}</p>
                                {{ message.content }}
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>

    </div>
{% endblock %}
{% block javascripts %}
    <script src="{{ asset('build/message.js') }}"></script>
{% endblock %}

templates/core/message/mailBox.html.twig
{% extends 'base.html.twig' %}

{% block title %}Search{% endblock %}
{% block stylesheets %}
    <link href="{{ asset('build/profile.css') }}" rel="stylesheet" />
    <link href="{{ asset('build/message.css') }}" rel="stylesheet" />
{% endblock %}
{% block body %}
<div class="containerMessage">
 <div class="row">
		<div class="col-md-offset-1 col-md-10 ">
			<div id="mailBox">
				{% if messages|length == 0 %}
					<div class="row">
						<div class="col-md-offset-1 col-md-10 ">
							<div id="empty">
								<p>Vous n'avez aucun messsage !</p>
							</div>
						</div>
					</div>
				{% endif %}
				{% for message in messages %}
					{% if message.userSender.id == idUser %}
						<div class="row">
							<div class="col-md-offset-1 col-md-10 ">
								<div>
									<a href="{{ path('app_message_send', { 'serviceId': message.serviceId, 'receiverId': message.userReceiver.id }) }}">
									<div id="silhouette" class="col-xs-1">
										{% if message.userReceiver.image == null %}
											<img class="img-responsive img-circle img-responsive" src="{{ asset('build/static/silhouette.png') }}">
										{% else %}
											<img class="img-responsive img-circle img-responsive"  src="{{asset('build/uploads/pictures/optimized/' ~ message.userReceiver.image.image) }}">
										{% endif %}
									</div>
									<div class="col-md-offset-1 col-md-2 name">
										{{  message.userReceiver.firstName }}
									</div>
									<div class="col-md-2 content">
										{{ message.content }}
									</div>
									</a>
								</div>
							</div>
						{% else %}
							<div class="row">
							<div class="col-md-offset-1 col-md-10 ">
								<div>
									<a href="{{ path('app_message_send', { 'serviceId': message.serviceId, 'receiverId': message.userSender.id }) }}">
										<div id="silhouette" class="col-xs-1">
											{% if message.userSender.image == null %}
											<img class="img-responsive img-circle img-responsive" src="{{ asset('build/static/silhouette.png') }}">
											{% else %}
												<img class="img-responsive img-circle img-responsive"  src="{{asset('build/uploads/pictures/optimized/' ~ message.userSender.image.image) }}">
											{% endif %}
										</div>

										<div class="col-md-offset-1 col-md-2 name">
										{{ message.userSender.firstName }}
										</div>
										<div class="col-md-2 content">
										{{ message.content }}
										</div>
									</a>
								</div>
							</div>
						{% endif %}
					</div>
					<hr/>
				{% endfor %}
			</div>
		</div>
	</div>
</div>
{% endblock %}
{% block javascripts %}
    <script src="{{ asset('build/message.js') }}"></script>
{% endblock %}

templates/core/message/message.html.twig
{% extends 'base.html.twig' %}

{% block title %}Search{% endblock %}
{% block stylesheets %}
    <link href="{{ asset('build/message.css') }}" rel="stylesheet" />
{% endblock %}
{% block body %}
    <div class="containerMessage">
    <div class="row">
    <div class="col-md-3 col-md-offset-1">
        <div class="panel-body shadow Compte">
            <img class="img-responsive img-circle img-responsive" id="silouhetteConversation" src="{{asset('build/static/silhouette.png') }}">

        </div>
    </div>
    <div id="conversation-message" class="col-md-offset-1 col-md-6">
    <div id="bloc-message-conversation" class="panel-body shadow Compte">
        {{ form_start(form) }}
        {{ form_row(form.content, { 'attr': { 'class' : 'form-control' }} ) }}
        {{ form_errors(form.content, { 'attr': { 'class' : 'form-control' }} ) }}
        {{ form_errors(form.content, { 'attr': { 'class' : 'form-control' }} ) }}
        {{ form_row(form.save, { 'attr': { 'class' : 'btn btn-group pull-right' }} ) }}
        {{ form_rest(form, { 'attr': { 'class' : 'form-control' }} ) }}
        {{ form_end(form, { 'attr': { 'class' : 'form-control' }} ) }}
    </div>

{% endblock %}
{% block javascripts %}
    <script src="{{ asset('build/message.js') }}"></script>
{% endblock %}